spring.application.name=ambulance-backend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ambulance_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret (In production, inject this via environment variable)
jwt.secret=4f7831cf65d911b33b95a82fa20967393437295ab0ba4c9d5af13702a0a256a9
jwt.expiration=86400000

# Server port
server.port=8080
logging.level.org.springframework.security=TRACE

